Close all HandleTie servants created during import
ome/omero-insight pull request #394
Opened 2023-08-25 11:47 UTC by jburel

This PR replaces #354

Run an import of one or multiple filesets and watch the creation/deletion of HandleTie servants server-side e.g. using ``tail -F Blitz-0.log  | grep HandleTie.``
All the handles should now be closed and the service closed.
Thumbnails are no longer loaded

To test:
* regular import of single files
* regular import of directories (1-10 & >50 to test the lightfileimport)
* import of broken files (failing server-side)
* import of HCS data
* import of some images which take longer to process on the server side and closing insight before the server side import is finished.

2023-08-28 11:36 UTC, sbesson requested changes
Tested against a remote OMERO server in a separate geographical region using a local build of OMERO.insight from the HEAD of this PR across the scenarios described in the description, specifically:
- two folders containing each 10 & 30 fake files
- a `plate.fake` file with an accompanying `plate.fake.ini` with `plateRows=4`, `plateCols=4` and `fields=2`
- a `slow.fake` file with an accompanying `slow.fake.ini` with `sleepOpenBytes=30000`
- an OME-XML file with an incorrect detector settings reference, currently failing import side
[wrong-detector-settings-mk1.ome.xml.zip](https://github.com/ome/omero-insight/files/12453761/wrong-detector-settings-mk1.ome.xml.zip)

All scenarios were tested individually as well as using combinations and the logs of the server were monitored using the command mentioned in the description.

> regular import of directories (1-10 & >50 to test the lightfileimport)

50 files was the threshold I remembered for the switch to the light file import UI but after verification the current limit is 100. This threshold is configurable using the `importer.xml` https://github.com/ome/omero-insight/blob/40b4f79d484a3e5193ca7c6b5508b1950ff3fb97/src/config/importer.xml#L41 and this value was lowered to 20 for the sake of my testing.

Confirmed that in all scenarios above, all the `HandleTie` servants are appropriately closed when the import completes and no leftover servant ends up being unregistered when closing OMERO.insight and terminating the session.
The only exception to this rule was the testing of the early closure of the importer/insight client after uploading a sample file with a long-processing time (`slow.fake`).  In that case, the servant is not cleaned until the end of the server-side import steps as expected.

A few inline comments/clarifications related to code review. Possibly the biggest impact outside the scope of the original fix is that the `View` button and the checkbox in the standard importer have disappeared.

With OMERO.insight 5.8.1,
<img width="1153" alt="Screenshot 2023-08-28 at 11 53 04" src="https://github.com/ome/omero-insight/assets/1355463/a70ae318-ce97-4f44-8dc3-9c233c57945a">
<img width="1197" alt="Screenshot 2023-08-28 at 11 53 35" src="https://github.com/ome/omero-insight/assets/1355463/68fd1f6a-48ee-42d8-a5d0-f610e974bd1c">


With this PR
<img width="1197" alt="Screenshot 2023-08-28 at 11 54 08" src="https://github.com/ome/omero-insight/assets/1355463/28ed9ea0-1e6b-42ca-9e28-560e3fe11320">
<img width="1197" alt="Screenshot 2023-08-28 at 11 54 21" src="https://github.com/ome/omero-insight/assets/1355463/0c394638-bcea-4964-bb55-509f3a32e37f">


For import failures, the cross icon is still visible and the `Failed` button gives access to the import logs

<img width="1197" alt="Screenshot 2023-08-28 at 12 08 24" src="https://github.com/ome/omero-insight/assets/1355463/d6ff176a-a2ba-46ee-ace0-50c04e601546">

I will leave @dominikl to perform his own testing and add his comments. In addition to the above, I would like to add a scenario testing the light UI import with a mixed case of files with successful imports and failures to confirm the statuses are as expected. But that can be scheduled for another round of testing especially if additional commits are added.

2023-08-28 11:36 UTC, sbesson commented on src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
> +		    image = result;
This call was not present in the original logic of `formatResult` and is not present in `LightFileImportComponent`. What is its function?

2023-08-28 11:36 UTC, sbesson commented on src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ImagesImporter.java
> +                public void doCall() { importFile(f, false); }
Should `final boolean b = index == n;` be removed if it's no longer used?

2023-08-28 11:36 UTC, sbesson commented on src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
> +				ImporterAgent.getRegistry().getLogger().info(this, msg);
Should this be a `warn` instead? I assume in most cases we are exception `closeImport` to complete without exceptions?

2023-08-28 12:06 UTC, jburel commented on src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
> +		    image = result;
that's  a leftover from a previous attempt. I will remove it

2023-08-28 12:07 UTC, jburel commented on src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ImagesImporter.java
> +                public void doCall() { importFile(f, false); }
It can, and the underline method could also be changed i.e. no need to pass a boolean.

2023-08-28 12:26 UTC, jburel commented on src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
> +		    image = result;
This method is invoked before the "setStatus" and follow a similar logic
```
if (image instanceof ImportException)
            result = image;
        if (result instanceof ImportException) {
```
Light import could be cleaned up too

2023-08-28 12:44 UTC, jburel commented on src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ImagesImporter.java
> +                public void doCall() { importFile(f, false); }
done

2023-08-28 12:44 UTC, jburel commented on src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
> +		    image = result;
sorted

2023-08-29 09:16 UTC, sbesson approved these changes
Retested with the last commits using all scenarios above as well as a directory using the light UI import with a mixture of successes and failures. Everything works as expected. The completion icon/button are displayed in the importer UI and all servants are unregistered server-side.

2023-08-30 09:12 UTC, dominikl approved these changes
Looks good. Tested different scenarios: Few images (with detailed info), many images (with just the summary, set limit to 20 like @sbesson mentioned). Plates. Multiple import tabs. Closing Insight after "File upload" step, etc. UI still behaves like expected. And there's one "Unregistered servant" for each "Added servant" in the Blitz log.
👍

2023-09-07 15:21 UTC, merged